import type { Project } from "@/content/types";

const projectCatalog = [
  {
    slug: "auto-email-system",
    name: "Auto Email System",
    kicker: "Personal Attention Filter",
    tagline: "A private inbox command center that reads my mail, separates real signals from noise, and only interrupts me when a message matters.",
    story: "I built it because checking multiple inboxes was stealing focus. New mail becomes Important, Secondary, or Ignore; only the first two are allowed to reach me through WeChat.",
    category: "software",
    stack: ["React", "Express", "IMAP", "WeChat"],
    sourceUrl: "https://github.com/Ha22yX/auto-email-system",
    files: [
      { kind: "folder", name: "Auto Email System" },
      { kind: "folder", name: "server" },
      { kind: "folder", name: "src" },
      { kind: "file", label: "MD", name: "README.md" },
      { kind: "file", label: "TS", name: "imapflow.ts" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/auto-email-system" },
    ],
  },
  {
    slug: "bridge-us-v2",
    name: "Bridge US V2",
    kicker: "Student-Life Mutual Aid Platform",
    tagline: "A social platform for students studying in the United States, built to make help easier to find and expensive mistakes easier to avoid.",
    story: "Bridge US is about reducing friction and loneliness in study-abroad life. Posts, AI answers, moderation, and translation help students ask, share, and understand faster.",
    category: "software",
    stack: ["React", "FastAPI", "Tailwind", "AI Q&A"],
    sourceUrl: "https://github.com/Ha22yX/Bridge-US-V2",
    websiteUrl: "https://bridge-us.org/",
    files: [
      { kind: "folder", name: "Bridge US V2" },
      { kind: "folder", name: "FrontEnd" },
      { kind: "folder", name: "BackEnd" },
      { kind: "file", label: "API", name: "FastAPI.py" },
      { kind: "shortcut", label: "WEB", name: "bridge-us.org", href: "https://bridge-us.org/" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/Bridge-US-V2" },
    ],
  },
  {
    slug: "mother-ship-docking-drone-system",
    name: "Mother-Ship Docking Drone System",
    kicker: "Layered Drone Localization",
    tagline: "A docking research system that combines GPS, UWB, and vision so two drones can understand their relative position through every stage of approach.",
    story: "GPS brings the drones into range, UWB narrows the approach, and vision handles the final high-precision window where centimeters matter.",
    category: "robotics",
    stack: ["PX4", "UWB", "AprilTag", "Python"],
    sourceUrl: "https://github.com/Ha22yX/Mother-Ship-Docking-Drone-System",
    websiteUrl: "https://isef.rosebeg.com/",
    files: [
      { kind: "folder", name: "Docking Drone" },
      { kind: "folder", name: "hardware" },
      { kind: "folder", name: "gps_drift_test" },
      { kind: "file", label: "PY", name: "MAVLink.py" },
      { kind: "shortcut", label: "WEB", name: "isef.rosebeg.com", href: "https://isef.rosebeg.com/" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/Mother-Ship-Docking-Drone-System" },
    ],
  },
  {
    slug: "dxf-auto-shape-tool",
    name: "Surfboard Vacuum Table DXF Generator",
    kicker: "Factory Workflow Automation",
    tagline: "A production tool made for my father's surfboard-machine company, replacing repetitive manual vacuum-hole layout with a controllable DXF generator.",
    story: "Each new surfboard mold used to mean hand-designing suction holes. Now the user imports a DXF outline, selects the contour, tunes parameters, and exports a ready file.",
    category: "creative-tool",
    stack: ["Python", "FastAPI", "ezdxf", "SVG"],
    sourceUrl: "https://github.com/Ha22yX/dxf-auto-shape-tool",
    files: [
      { kind: "folder", name: "DXF Generator" },
      { kind: "folder", name: "backend" },
      { kind: "folder", name: "frontend" },
      { kind: "file", label: "DXF", name: "output.dxf" },
      { kind: "file", label: "PY", name: "main.py" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/dxf-auto-shape-tool" },
    ],
  },
  {
    slug: "esp32-sound-radar",
    name: "ESP32 Sound Radar",
    kicker: "Sound Direction Experiment",
    tagline: "A small hardware experiment built around a simple question: if sound reaches microphones at different times, can a device infer where it came from?",
    story: "Four microphones compare the timing of the same sound wave, while filtering, thresholds, and similarity checks keep random noise from becoming a false direction.",
    category: "electronics",
    stack: ["ESP32-S3", "Arduino", "I2S", "TDOA"],
    sourceUrl: "https://github.com/Ha22yX/ESP32-Sound-Radar",
    files: [
      { kind: "folder", name: "ESP32 Radar" },
      { kind: "folder", name: "src" },
      { kind: "file", label: "INO", name: "sound_radar.ino" },
      { kind: "shortcut", label: "WEB", name: "local-dashboard" },
      { kind: "file", label: "TFT", name: "direction.ui" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/ESP32-Sound-Radar" },
    ],
  },
  {
    slug: "sat-ai-tutor",
    name: "SAT AI Tutor",
    kicker: "Human-Like Study Companion",
    tagline: "An SAT practice platform I built for myself because static answer explanations felt too long, too passive, and too far from how a real teacher helps.",
    story: "After each question, the review highlights evidence, eliminates choices, and points out traps. AI then turns mistakes into plans, weak-point discovery, and targeted practice.",
    category: "software",
    stack: ["Next.js", "Flask", "OpenAI", "Docker"],
    sourceUrl: "https://github.com/Ha22yX/SAT-AI-Tutor",
    websiteUrl: "https://sat.rosebeg.com/auth/login?demo=1",
    files: [
      { kind: "folder", name: "SAT AI Tutor" },
      { kind: "folder", name: "frontend" },
      { kind: "folder", name: "sat_platform" },
      { kind: "file", label: "PDF", name: "question-bank.pdf" },
      { kind: "shortcut", label: "GHCR", name: "container.url" },
      { kind: "shortcut", label: "WEB", name: "demo.view", href: "https://sat.rosebeg.com/auth/login?demo=1" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/SAT-AI-Tutor" },
    ],
  },
  {
    slug: "photoback",
    name: "PhotoBack",
    kicker: "Photography Delivery Workflow",
    tagline: "A photo delivery platform built from my own church photography workflow, so every event can have one clean link instead of endless manual sending.",
    story: "I upload an event gallery once, share a private project link, and people can find and save the photos they want. It makes delivery calmer for both sides.",
    category: "creative-tool",
    stack: ["Flask", "SQLite", "Pillow", "Google Drive"],
    sourceUrl: "https://github.com/Ha22yX/PhotoBack",
    websiteUrl: "https://photoback.rosebeg.com/view/8b6ab9d9",
    files: [
      { kind: "folder", name: "PhotoBack" },
      { kind: "folder", name: "app" },
      { kind: "folder", name: "migrations" },
      { kind: "file", label: "IMG", name: "gallery.ui" },
      { kind: "shortcut", label: "WEB", name: "demo.view", href: "https://photoback.rosebeg.com/view/8b6ab9d9" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/PhotoBack" },
    ],
  },
  {
    slug: "dayvault",
    name: "DayVault",
    kicker: "Personal Life-Archive Recorder",
    tagline: "An ultra-low-power microphone designed to capture an entire day, then recharge and transfer its recordings automatically when connected to a computer.",
    story: "AI has become powerful enough that a personal record of every day no longer feels impossible. I built DayVault to collect what I say with almost no daily friction: carry it all day, plug it in at night to charge and offload the audio, then eventually transcribe the files and use a language model to summarize the day. The long-term goal is an archive of my life, one ordinary day at a time.",
    category: "electronics",
    stack: ["STM32L452", "dual PDM microphones", "microSD", "USB-C", "RTC"],
    sourceUrl: "https://github.com/Ha22yX/DayVault",
    files: [
      { kind: "folder", name: "DayVault" },
      { kind: "folder", name: "hardware" },
      { kind: "file", name: "README.md" },
      { kind: "file", name: "voice-logger.kicad" },
      { kind: "shortcut", name: "github.url", href: "https://github.com/Ha22yX/DayVault" },
    ],
  },
  {
    slug: "gridopoly",
    name: "Gridopoly",
    kicker: "Cashless Smart Board",
    tagline: "A modular electronic board-game platform inspired by a Monopoly night with friends, designed to make transactions faster without losing the physical tabletop experience.",
    story: "While traveling with friends one summer, I noticed that counting cash and handling every transaction kept interrupting the game. I came home wondering whether I could build a fully electronic board myself, then started defining the product and drawing its circuit boards. Gridopoly turns that idea into programmable smart tiles with RFID, color displays, lighting, and shared networking.",
    category: "electronics",
    stack: ["ESP32-S3", "RS485", "125 kHz RFID", "ST7789", "addressable LEDs"],
    sourceUrl: "https://github.com/Ha22yX/Gridopoly",
    files: [
      { kind: "folder", name: "Gridopoly" },
      { kind: "folder", name: "hardware" },
      { kind: "folder", name: "firmware" },
      { kind: "file", name: "README.md" },
      { kind: "shortcut", name: "github.url", href: "https://github.com/Ha22yX/Gridopoly" },
    ],
  },
  {
    slug: "onlypt-recruiting",
    name: "onlyPT Recruiting",
    kicker: "Pro-Bono Business Website",
    tagline: "A polished recruiting website and lightweight CMS I designed and built free of charge for my church's Youth Pastor and his independent physical-therapy recruiting business.",
    story: "My Youth Pastor is also a physical-therapy recruiter and a close friend. One evening at his house, he showed me the business website he had made himself. I joked that it looked terrible and offered to build him a better one for free. I started the next night and spent more than a month shaping every page and detail by hand. Seeing how excited he was, and watching the finished site bring him real business, made this one of my most personally rewarding projects.",
    category: "software",
    stack: ["Flask", "Jinja", "Vanilla CSS", "JavaScript", "CMS"],
    sourceUrl: "https://github.com/Ha22yX/onlypt-recruiting",
    websiteUrl: "https://onlypt.co/",
    files: [
      { kind: "folder", name: "onlyPT Recruiting" },
      { kind: "folder", name: "templates" },
      { kind: "folder", name: "static" },
      { kind: "file", label: "PY", name: "app.py" },
      { kind: "shortcut", label: "WEB", name: "onlypt.co", href: "https://onlypt.co/" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/onlypt-recruiting" },
    ],
  },
] satisfies readonly Project[];

const projectOrder = [
  "gridopoly",
  "onlypt-recruiting",
  "dayvault",
  "bridge-us-v2",
  "esp32-sound-radar",
  "mother-ship-docking-drone-system",
  "auto-email-system",
  "photoback",
  "sat-ai-tutor",
  "dxf-auto-shape-tool",
] as const;

export const projects = projectOrder.map((slug) => {
  const project = projectCatalog.find((candidate) => candidate.slug === slug);
  if (!project) throw new Error(`Unknown portfolio project: ${slug}`);
  return project;
}) satisfies readonly Project[];
