import type { Project } from "@/content/types";

export const projects = [
  {
    slug: "auto-email-system",
    name: "Auto Email System",
    kicker: "Personal Attention Filter",
    tagline: "A private inbox command center that reads my mail, separates real signals from noise, and only interrupts me when a message matters.",
    story: "I built it because checking multiple inboxes was stealing focus. New mail becomes Important, Secondary, or Ignore; only the first two are allowed to reach me through WeChat.",
    category: "software",
    stack: ["React", "Express", "IMAP", "WeChat"],
    sourceUrl: "https://github.com/Ha22yX/auto-email-system",
    files: [
      { kind: "folder", name: "Auto Email System" },
      { kind: "folder", name: "server" },
      { kind: "folder", name: "src" },
      { kind: "file", label: "MD", name: "README.md" },
      { kind: "file", label: "TS", name: "imapflow.ts" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/auto-email-system" },
    ],
  },
  {
    slug: "bridge-us-v2",
    name: "Bridge US V2",
    kicker: "Student-Life Mutual Aid Platform",
    tagline: "A social platform for students studying in the United States, built to make help easier to find and expensive mistakes easier to avoid.",
    story: "Bridge US is about reducing friction and loneliness in study-abroad life. Posts, AI answers, moderation, and translation help students ask, share, and understand faster.",
    category: "software",
    stack: ["React", "FastAPI", "Tailwind", "AI Q&A"],
    sourceUrl: "https://github.com/Ha22yX/Bridge-US-V2",
    websiteUrl: "https://bridge-us.org/",
    files: [
      { kind: "folder", name: "Bridge US V2" },
      { kind: "folder", name: "FrontEnd" },
      { kind: "folder", name: "BackEnd" },
      { kind: "file", label: "API", name: "FastAPI.py" },
      { kind: "shortcut", label: "WEB", name: "bridge-us.org", href: "https://bridge-us.org/" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/Bridge-US-V2" },
    ],
  },
  {
    slug: "mother-ship-docking-drone-system",
    name: "Mother-Ship Docking Drone System",
    kicker: "Layered Drone Localization",
    tagline: "A docking research system that combines GPS, UWB, and vision so two drones can understand their relative position through every stage of approach.",
    story: "GPS brings the drones into range, UWB narrows the approach, and vision handles the final high-precision window where centimeters matter.",
    category: "robotics",
    stack: ["PX4", "UWB", "AprilTag", "Python"],
    sourceUrl: "https://github.com/Ha22yX/Mother-Ship-Docking-Drone-System",
    websiteUrl: "https://isef.rosebeg.com/",
    files: [
      { kind: "folder", name: "Docking Drone" },
      { kind: "folder", name: "hardware" },
      { kind: "folder", name: "gps_drift_test" },
      { kind: "file", label: "PY", name: "MAVLink.py" },
      { kind: "shortcut", label: "WEB", name: "isef.rosebeg.com", href: "https://isef.rosebeg.com/" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/Mother-Ship-Docking-Drone-System" },
    ],
  },
  {
    slug: "dxf-auto-shape-tool",
    name: "Surfboard Vacuum Table DXF Generator",
    kicker: "Factory Workflow Automation",
    tagline: "A production tool made for my father's surfboard-machine company, replacing repetitive manual vacuum-hole layout with a controllable DXF generator.",
    story: "Each new surfboard mold used to mean hand-designing suction holes. Now the user imports a DXF outline, selects the contour, tunes parameters, and exports a ready file.",
    category: "creative-tool",
    stack: ["Python", "FastAPI", "ezdxf", "SVG"],
    sourceUrl: "https://github.com/Ha22yX/dxf-auto-shape-tool",
    files: [
      { kind: "folder", name: "DXF Generator" },
      { kind: "folder", name: "backend" },
      { kind: "folder", name: "frontend" },
      { kind: "file", label: "DXF", name: "output.dxf" },
      { kind: "file", label: "PY", name: "main.py" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/dxf-auto-shape-tool" },
    ],
  },
  {
    slug: "esp32-sound-radar",
    name: "ESP32 Sound Radar",
    kicker: "Sound Direction Experiment",
    tagline: "A small hardware experiment built around a simple question: if sound reaches microphones at different times, can a device infer where it came from?",
    story: "Four microphones compare the timing of the same sound wave, while filtering, thresholds, and similarity checks keep random noise from becoming a false direction.",
    category: "electronics",
    stack: ["ESP32-S3", "Arduino", "I2S", "TDOA"],
    sourceUrl: "https://github.com/Ha22yX/ESP32-Sound-Radar",
    files: [
      { kind: "folder", name: "ESP32 Radar" },
      { kind: "folder", name: "src" },
      { kind: "file", label: "INO", name: "sound_radar.ino" },
      { kind: "shortcut", label: "WEB", name: "local-dashboard" },
      { kind: "file", label: "TFT", name: "direction.ui" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/ESP32-Sound-Radar" },
    ],
  },
  {
    slug: "sat-ai-tutor",
    name: "SAT AI Tutor",
    kicker: "Human-Like Study Companion",
    tagline: "An SAT practice platform I built for myself because static answer explanations felt too long, too passive, and too far from how a real teacher helps.",
    story: "After each question, the review highlights evidence, eliminates choices, and points out traps. AI then turns mistakes into plans, weak-point discovery, and targeted practice.",
    category: "software",
    stack: ["Next.js", "Flask", "OpenAI", "Docker"],
    sourceUrl: "https://github.com/Ha22yX/SAT-AI-Tutor",
    websiteUrl: "https://sat.rosebeg.com/auth/login?demo=1",
    files: [
      { kind: "folder", name: "SAT AI Tutor" },
      { kind: "folder", name: "frontend" },
      { kind: "folder", name: "sat_platform" },
      { kind: "file", label: "PDF", name: "question-bank.pdf" },
      { kind: "shortcut", label: "GHCR", name: "container.url" },
      { kind: "shortcut", label: "WEB", name: "demo.view", href: "https://sat.rosebeg.com/auth/login?demo=1" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/SAT-AI-Tutor" },
    ],
  },
  {
    slug: "photoback",
    name: "PhotoBack",
    kicker: "Photography Delivery Workflow",
    tagline: "A photo delivery platform built from my own church photography workflow, so every event can have one clean link instead of endless manual sending.",
    story: "I upload an event gallery once, share a private project link, and people can find and save the photos they want. It makes delivery calmer for both sides.",
    category: "creative-tool",
    stack: ["Flask", "SQLite", "Pillow", "Google Drive"],
    sourceUrl: "https://github.com/Ha22yX/PhotoBack",
    websiteUrl: "https://photoback.rosebeg.com/view/8b6ab9d9",
    files: [
      { kind: "folder", name: "PhotoBack" },
      { kind: "folder", name: "app" },
      { kind: "folder", name: "migrations" },
      { kind: "file", label: "IMG", name: "gallery.ui" },
      { kind: "shortcut", label: "WEB", name: "demo.view", href: "https://photoback.rosebeg.com/view/8b6ab9d9" },
      { kind: "shortcut", label: "URL", name: "github.url", href: "https://github.com/Ha22yX/PhotoBack" },
    ],
  },
  {
    slug: "dayvault",
    name: "DayVault",
    kicker: "All-Day Voice Logger",
    tagline: "A compact all-day voice logger designed around low-power recording, dual digital microphones, removable storage, and dependable timekeeping.",
    story: "DayVault turns a complete embedded audio-capture concept into documented hardware: STM32L452 control, two PDM microphones, microSD storage, USB-C, and an RTC in a compact wearable-oriented design.",
    category: "electronics",
    stack: ["STM32L452", "dual PDM microphones", "microSD", "USB-C", "RTC"],
    sourceUrl: "https://github.com/Ha22yX/DayVault",
    files: [
      { kind: "folder", name: "DayVault" },
      { kind: "folder", name: "hardware" },
      { kind: "file", name: "README.md" },
      { kind: "file", name: "voice-logger.kicad" },
      { kind: "shortcut", name: "github.url", href: "https://github.com/Ha22yX/DayVault" },
    ],
  },
  {
    slug: "gridopoly",
    name: "Gridopoly",
    kicker: "Modular Smart Board Platform",
    tagline: "A modular electronic board-game platform made from rearrangeable smart tiles that sense pieces, display state, and communicate over a shared bus.",
    story: "Each tile combines RFID, a color display, addressable light, and RS485 networking around an ESP32-S3 so physical board layouts can become programmable game systems.",
    category: "electronics",
    stack: ["ESP32-S3", "RS485", "125 kHz RFID", "ST7789", "addressable LEDs"],
    sourceUrl: "https://github.com/Ha22yX/Gridopoly",
    files: [
      { kind: "folder", name: "Gridopoly" },
      { kind: "folder", name: "hardware" },
      { kind: "folder", name: "firmware" },
      { kind: "file", name: "README.md" },
      { kind: "shortcut", name: "github.url", href: "https://github.com/Ha22yX/Gridopoly" },
    ],
  },
] satisfies readonly Project[];
